// Everything here comes from public GitHub info and project READMEs — edit freely.
export const profile = {
  name: 'Md Muhimenul Tareque',
  short: 'Muhimenul Tareque',
  role: 'Software Engineer',
  location: 'Bangladesh',
  email: 'mmtareque@yahoo.com',
  github: 'https://github.com/mmTareque01',
  linkedin: 'https://www.linkedin.com/in/mmtareque/',
  upwork: 'https://www.upwork.com/freelancers/~01d7acd506a83cc8b6',
  status: 'Currently engineering at Mugen Infotech',
};

// Featured case studies. `art` picks the generative cover; `shots` use real screenshots.
// `client` marks employer/client work (private codebase, no source links).
export const work = [
  {
    id: 'kasen',
    title: 'Kasen Grant Management',
    tag: 'Grant management platform',
    year: 'Mugen · client',
    client: true,
    blurb: 'An end-to-end grant platform for a Japanese client — applications, reviews, approvals and payments in one system. A React front end over a Go (Gin) API, fully containerised, with serverless jobs on AWS Lambda.',
    points: ['1,500+ commits of my own since Oct 2025', 'Role-based authorisation across every route', 'Payment-gateway migration & PDF/Excel outputs'],
    stack: ['React', 'Vite', 'Go', 'Gin', 'Docker', 'AWS Lambda'],
    art: 'flow', c1: '#5ef2ff', c2: '#2b6bff',
  },
  {
    id: 'meet',
    title: 'Jacos Meet',
    tag: 'AI video conferencing',
    year: 'Jacos · via Mugen',
    client: true,
    blurb: 'A customised Jitsi Meet deployment with an AI layer: live transcription with Faster Whisper, AI meeting summaries and action items, plus a desktop annotation app for drawing over shared screens.',
    points: ['Live captions over WebSockets', 'LLM summaries & action items', 'Electron + native macOS annotation overlay'],
    stack: ['Jitsi', 'WebRTC', 'Docker', 'Faster Whisper', 'LLMs', 'Electron', 'Swift'],
    art: 'video', c1: '#7dffb2', c2: '#1f8f6a',
  },
  {
    id: 'potacon',
    title: 'Potacon',
    tag: 'Calling platform · web + mobile',
    year: 'Jacos · via Mugen',
    client: true,
    blurb: 'A communication platform with WebRTC voice and video calling, contacts and call history — a Laravel web app plus a React Native app for Android and iOS, with push notifications and a Gemini-powered AI secretary.',
    points: ['React Native app with Jitsi calling', 'Firebase push + Google sign-in', 'AI secretary for schedules & chat'],
    stack: ['Laravel', 'React Native', 'WebRTC', 'Firebase', 'Gemini'],
    art: 'call', c1: '#ffb86b', c2: '#ff5d8f',
  },
  {
    id: 'edupathway',
    title: 'EduPathway',
    tag: 'Multi-tenant SaaS',
    year: 'Tronixora',
    blurb: 'A multi-tenant platform for study-abroad consultancies. Every agency gets its own branded public website, a student portal and an admissions CRM — all served from a single deployment.',
    points: ['Tenant-aware routing & branding', 'Student portal + admissions CRM', 'Rich-text content & media pipeline'],
    stack: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'Cloudinary', 'TipTap'],
    art: 'tenants', c1: '#8ea8ff', c2: '#5b3bff',
  },
  {
    id: 'tourflow',
    title: 'TourFlow',
    tag: 'Tour operator SaaS',
    year: 'Tronixora',
    blurb: 'Everything a group-tour company runs on: tours with hotels, guides, transport and rooms, bookings, leads, payments, expenses and staff — plus a website builder, public booking pages, reviews and subscription plans for each tenant.',
    points: ['Multi-tenant with plans & upgrades', 'Public booking + review links', 'Rate-limited public API with API keys'],
    stack: ['Next.js', 'Prisma', 'TanStack Query', 'Upstash Redis', 'react-pdf', 'Cloudinary'],
    art: 'route', c1: '#ffd166', c2: '#ff7a45',
  },
  {
    id: 'dentalflow',
    title: 'DentalFlow',
    tag: 'Clinic management SaaS',
    year: 'Tronixora',
    blurb: 'Mobile-first software for dental clinics: patients, appointments, custom e-prescriptions, offline SMS confirmations and one-tap PDF / print / share of prescriptions.',
    points: ['Mobile-first scheduling', 'Server-side PDF prescriptions', 'Offline SMS confirmations'],
    stack: ['Next.js 15', 'React 19', 'Prisma', 'PostgreSQL', 'NextAuth', 'TanStack Query'],
    art: 'pulse', c1: '#7dffb2', c2: '#00a37a',
    links: { code: 'https://github.com/mmTareque01/dental-flow' },
  },
  {
    id: 'reels',
    title: 'Reels Maker',
    tag: 'AI video pipeline',
    year: 'Automation',
    blurb: 'Product JSON in, finished 1080×1920 reel out. An LLM writes the script, keywords pull stock b-roll, text-to-speech records the voiceover and Whisper burns in word-timed captions.',
    points: ['LLM script generation', 'TTS voiceover + Whisper captions', 'Automated vertical video render'],
    stack: ['Python', 'LLM APIs', 'TTS', 'Whisper', 'Video rendering'],
    art: 'wave', c1: '#ff6ad5', c2: '#8b5cff',
  },
  {
    id: 'agents',
    title: 'Personal Assistant',
    tag: 'Multi-agent system',
    year: 'AI agents',
    blurb: 'A self-hosted assistant running on a Raspberry Pi: 28 n8n workflows in five layers — watchers for mail, Slack, GitHub and calendar, an orchestrator brain, and specialist sub-agents that report over Telegram.',
    points: ['28 workflows · 5 layers', 'Orchestrator + specialist sub-agents', 'Runs on a Raspberry Pi'],
    stack: ['n8n', 'PostgreSQL', 'Gemini', 'Telegram', 'Raspberry Pi'],
    art: 'graph', c1: '#ffb86b', c2: '#ff5d5d',
  },
  {
    id: 'motion',
    title: 'Motion Commerce',
    tag: 'WebGL storefronts',
    year: 'Creative dev',
    blurb: 'Three immersive storefronts — a perfume maison with real-time glass and a flower-to-flacon sequence, headphones that explode into parts on scroll, and a toy shop you can play with.',
    points: ['Real-time 3D with Three.js', 'Scroll-driven GSAP choreography', 'Working cart & product flows'],
    stack: ['Three.js', 'WebGL', 'GSAP', 'Lenis', 'Vite'],
    shots: ['/work/aurele.jpg', '/work/nova-2.jpg', '/work/wobble.jpg'],
    c1: '#e9cf9b', c2: '#ff4f1f',
    links: {
      live: 'https://perfume-one-blond.vercel.app',
      live2: 'https://audio-store-one.vercel.app',
      code: 'https://github.com/mmTareque01/perfume',
    },
  },
];

// Archive tiles. `group` drives the filter chips.
export const more = [
  { group: 'Client', title: 'iSYS', desc: 'Inquiry management: public form, admin with status tracking, assignment and CSV/Excel export.', stack: 'Next.js · Prisma · MySQL' },
  { group: 'Client', title: 'Aurora System', desc: 'Scheduled Python agents for research, KPIs and operations, coordinated through Notion with Slack alerts.', stack: 'Python · Notion API · Slack' },
  { group: 'Client', title: 'Jacos Workspace', desc: 'Business workspace with Gmail & Zoho mail, calendar, AI scheduling and shareable links.', stack: 'CodeIgniter 4 · PHP' },
  { group: 'Client', title: 'InvoicePlane', desc: 'Mobile-first products, clients, quotations and invoices for small businesses in Japan.', stack: 'Next.js 16 · Prisma · MySQL' },
  { group: 'Client', title: 'Schedule', desc: 'A Japanese schedule app with voice input, designed for elderly users.', stack: 'Next.js 16 · Firebase' },
  { group: 'Client', title: 'FreshCatch', desc: 'Fresh-fish e-commerce with Stripe payments or cash on delivery.', stack: 'Next.js · Prisma · Stripe' },
  { group: 'Own', title: 'AI Post Scheduler', desc: 'Connect social accounts, let Claude draft posts and publish them on a schedule.', stack: 'Next.js · Claude API · cron' },
  { group: 'Own', title: 'OpenHub', desc: 'A home for open-source projects with search, admin analytics and bulk import.', stack: 'Next.js 16 · PostgreSQL' },
  { group: 'Own', title: 'MT Agro Foods', desc: 'Single-vendor e-commerce for homemade foods with guest checkout and COD.', stack: 'Next.js 16 · Prisma' },
  { group: 'Own', title: 'BD Medicine API', desc: 'Scraped medicine data served through a rate-limited public API.', stack: 'Next.js · Supabase · Redis' },
  { group: 'Own', title: 'Pod-Share', desc: 'Share files by link or QR code — no signup, optional password and expiry.', stack: 'React · Node', href: 'https://github.com/mmTareque01/pod-share' },
  { group: 'Own', title: 'Google Drive Finder', desc: 'Search and surface files across Google Drive fast.', stack: 'Next.js · TypeScript', href: 'https://github.com/mmTareque01/google-drive-finder' },
  { group: 'Own', title: 'SourceHub', desc: 'A ready-to-go React project structure with the essentials wired up.', stack: 'React · TypeScript', href: 'https://sourcehub-pink.vercel.app' },
  { group: 'Own', title: 'MT Care', desc: 'Patient registration and appointment management for healthcare.', stack: 'Next.js · TypeScript', href: 'https://mt-care.vercel.app' },
  { group: 'Own', title: 'Inventory', desc: 'Stock and product inventory management.', stack: 'React', href: 'https://inventory-beta.vercel.app' },
  { group: 'Own', title: 'Hospital Management', desc: 'Admin system for patients, doctors and records.', stack: 'React · Node', href: 'https://hospital-management-one-gamma.vercel.app' },
  { group: 'Own', title: 'Offline Caller', desc: 'A lightweight calling utility web app.', stack: 'React', href: 'https://offline-caller.vercel.app' },
  { group: 'Own', title: 'Blog CMS', desc: 'Headless content management for a blog.', stack: 'Strapi · Node', href: 'https://github.com/mmTareque01/blog-cms' },
  { group: 'Own', title: 'Blogger Automation', desc: 'Automated publishing through the Google Blogger API.', stack: 'Python', href: 'https://github.com/mmTareque01/blogger-api-automation' },
  { group: 'Own', title: 'Home Automation', desc: 'Controlling home appliances with a Raspberry Pi.', stack: 'Raspberry Pi · JS', href: 'https://github.com/mmTareque01/home_automation_using_rasberry_pi' },
  { group: 'Own', title: 'School Management', desc: 'School administration built with Ruby on Rails.', stack: 'Ruby on Rails', href: 'https://github.com/mmTareque01/school-management-using-ror' },
  { group: 'Own', title: 'E-commerce', desc: 'Storefront with a React client and Django back end.', stack: 'React · Django', href: 'https://github.com/mmTareque01/ecommerce-using-react-django' },
  { group: 'Own', title: 'Learning Blockchain', desc: 'Smart-contract experiments in Solidity.', stack: 'Solidity', href: 'https://github.com/mmTareque01/learning_blockchain' },
  { group: 'Own', title: 'Steganography', desc: 'Hiding messages inside images.', stack: 'PowerShell', href: 'https://github.com/mmTareque01/Steganography' },
];

export const oss = [
  {
    name: 'react-smooth-hash-link',
    cmd: 'npm i react-smooth-hash-link',
    desc: 'Fixes React Router’s missing scroll-to-#hash behaviour with a drop-in <HashLink>. Smooth-scrolls to the matching element, even ones rendered later.',
    href: 'https://github.com/mmTareque01/react-smooth-hash-link',
  },
  {
    name: 'make-express-api',
    cmd: 'npx make-express-api user',
    desc: 'A CLI inspired by Rails scaffolding: one command generates a full CRUD API module for Express — routes, controller and model.',
    href: 'https://github.com/mmTareque01/make-express-api',
  },
];

export const stack = [
  { group: 'Back end', items: ['Node.js', 'NestJS', 'Express', 'Django', 'Ruby on Rails', 'WebSockets', 'GraphQL', 'RabbitMQ'] },
  { group: 'Front end', items: ['TypeScript', 'React', 'Next.js', 'React Native', 'Redux', 'Tailwind', 'Three.js', 'GSAP'] },
  { group: 'Data', items: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Prisma', 'TypeORM', 'Sequelize'] },
  { group: 'Cloud & AI', items: ['Docker', 'AWS', 'Nginx', 'Linux', 'n8n', 'LLM APIs', 'Whisper', 'Python ML'] },
];

export const journey = [
  { when: 'Aug 2024 — Now', where: 'Mugen Infotech', what: 'Engineering for Japanese clients: the Kasen grant-management platform (React + Go), and for Jacos — Jacos Meet, Potacon web & mobile, iSYS and more.' },
  { when: 'Ongoing', where: 'Tronixora', what: 'Independent SaaS products — EduPathway, TourFlow, DentalFlow — and motion-rich web.' },
  { when: 'Ongoing', where: 'Freelance · Upwork', what: 'Shipping APIs, dashboards and automation for clients worldwide.' },
  { when: 'Previously', where: 'Quantic Dynamics', what: 'Software engineering on production web systems.' },
  { when: 'Previously', where: 'Abroadinquiry', what: 'Engineering for the study-abroad space.' },
  { when: '2020', where: 'GitHub', what: 'First public commit. 57 repositories later, still shipping.' },
];
